
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-rabbit 
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/shahin-salehi/on-prem-cluster
    targetRevision: dev
    path: rabbit
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated: {}