apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: postgres-db
  type: NodePort
  ports:
  - port: 6000 # service port 
    targetPort: 5432 # container port 
    nodePort: 32002 # external port

#https://stackoverflow.com/questions/49981601/difference-between-targetport-and-port-in-kubernetes-service-definition